### PR TITLE
Enforce password strength constraint

### PR DESCRIPTION
**Pull request by Pr0Ger**
We have server-side check for password strength, this PR will add client side validation with same restrictions

### CODE REVIEW

**Comment by TawR1024** [comment]
@Pr0Ger , is this PR still active ? If it actual, please update it and fix tests, otherwise close it.

**Comment by Pr0Ger** [comment]
@TawR1024 @kolsean Comrades, this PR is ready for your attention

**Review by kolsean — APPROVED** [review]
LGTM!

**Review by TawR1024 — APPROVED** [review]
LGTM !

**Pull request merged**
